### ISSUE TITLE
Imgur token stopped working

### ISSUE THREAD

**Issue by Astralcircle** [Earu/EasyChat#132]
It looks like your imgur token is no longer working, please update it to another one.

**Comment by Earu** [comment]
This is the third time in 2 years I have to change this token. I don't set any expiration date on it each time. Which leads me to believe that its either abused or imgur really doesnt like the traffic it has. 

I'd much rather be in favor of a way to deal with this other than imgur

**Comment by Astralcircle** [comment]
Maybe we should add a setting so that players can create their own token? I think this would solve the traffic problem.

**Comment by Earu** [comment]
In my experience that just leads to people not using this feature anymore. Already done with various other things. Setting up an account on a third party account and getting a token is:

- Scary for non IT versed people
- Requires trust
- Has friction (e.g most people won't do it because too much efforts)

**Comment by Earu** [comment]
https://github.com/Earu/EasyChat/commit/15b18373f7af9423253f2da4d51f54b6f8b48f88

Should work now, although it **will** most definitely break again eventually, imgur doesnt like us using the API like that it seems.
