### ISSUE TITLE
EasyChat Indicator doesn't activate

### ISSUE THREAD

**Issue by TheCyberGalaxy** [Earu/EasyChat#85]
I have a Problem where I can't active to Indicate something or someone, if I try to activate it, it deacivates.

I have a Youtube Video where you can watch on what I mean:
https://youtu.be/6TuGUsLtV58

**Comment by Earu** [comment]
Hey there, the setting disables itself because the key it's trying to assign is already bound to something different. If you're curious here's the code: https://github.com/Earu/EasyChat/blob/master/lua/easychat/modules/indications.lua#L289L294)

You have two options, either you unbind your middle mouse button from what it's binded to. Either you bind `+ec_indicate` to any other key in the console.

**Comment by TheCyberGalaxy** [comment]
Thank you very much Earu!
