### ISSUE TITLE
Unable to use ESC, console after attempting to enter chat.

### ISSUE THREAD

**Issue by Max-Spec** [Earu/EasyChat#87]
My friend, after trying to talk in chat, got frozen up, with no ability to press ESC but only leave the game. I have no idea why that happens, but I can try to ask about the error dump.

**Comment by Earu** [comment]
Linux?

**Comment by Max-Spec** [comment]
No. It's not Linux.

**Comment by Earu** [comment]
Could you provide the dump file for the crash ? Along with y the matching .txt

There is not much being done when pressing escape, essentially closing the gmod menu because it might open when escape is pressed and hiding the chatbox. If there's any crash it's very likely it's a garrysmod issue more than an EasyChat one.

**Comment by Max-Spec** [comment]
It was bound to sv_cheats 1. That's all.
It did make the chat work, but when opening the chat it still broke ESC and console, but that still didn't output anything into Gmod terminal.

**Comment by Max-Spec** [comment]
Oh well, I suppose that's out of the way now.
